name: Deploy Mossa

on:
  push:
    branches: [main]
  workflow_dispatch: {}

# Izin standar yang cukup untuk checkout dan eksekusi
permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          # Pastikan semua secrets ini sudah diisi di repo Anda!
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_CLOUDINARY_CLOUD_NAME: ${{ secrets.VITE_CLOUDINARY_CLOUD_NAME }}
          VITE_CLOUDINARY_UPLOAD_PRESET: ${{ secrets.VITE_CLOUDINARY_UPLOAD_PRESET }}
        run: npm run build

      - name: Fix SPA Routing (Copy index.html to 404.html)
        run: cp dist/index.html dist/404.html

      - name: Deploy to External Public Repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }} 
          external_repository: servant-id/mossain
          publish_branch: main 
          publish_dir: ./dist
          cname: mossain.servant.biz.id
          force_orphan: true 
          commit_message: "Release on Main ${{ github.event.head_commit.message }}"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'